export interface Lyrics {
  duration: number;
  content: string;
  startOfParagraph: null;
  startTime: number;
  pokemon: string;
}

const lyrics: Lyrics[] = [
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 4.62,
  },
  {
    duration: 0,
    content: 'How do you do the things you do?',
    startOfParagraph: null,
    startTime: 6.78,
  },
  {
    duration: 0,
    content: 'Share with me your secrets deep inside',
    startOfParagraph: null,
    startTime: 8.78,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 13.1,
  },
  {
    duration: 0,
    content: 'Are you loyal through and through?',
    startOfParagraph: null,
    startTime: 15.48,
  },
  {
    duration: 0,
    content: "And do you have a heart that's true?",
    startOfParagraph: null,
    startTime: 17.46,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 20.98,
  },
  {
    duration: 0,
    content: 'Yeah',
    startOfParagraph: null,
    startTime: 23.9,
  },
  {
    duration: 0,
    content: 'Yo',
    startOfParagraph: null,
    startTime: 31.84,
  },
  {
    duration: 0,
    content: 'Take a Normal type like Jigglypuff',
    startOfParagraph: null,
    startTime: 32.34,
    pokemon: 'Jigglypuff.png',
  },
  {
    duration: 0,
    content: "Against the ghostly Gengar a battle's real tough!",
    startOfParagraph: null,
    startTime: 34.5,
    pokemon: 'Gengar.png',
  },
  {
    duration: 0,
    content: "Thunderbolt's a great electric attack",
    startOfParagraph: null,
    startTime: 36.56,
  },
  {
    duration: 0,
    content: "'till you get ground down by a Marowak!",
    startOfParagraph: null,
    startTime: 39.0,
    pokemon: 'Marowak.png',
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 41.02,
  },
  {
    duration: 0,
    content: 'How do you do the things you do?',
    startOfParagraph: null,
    startTime: 42.56,
  },
  {
    duration: 0,
    content:
      "Don't ya bug me, with a Caterpie. For a Flying type the win's easy",
    startOfParagraph: null,
    startTime: 45.75,
    pokemon: 'Caterpie.png',
  },
  {
    duration: 0,
    content: 'Good luck',
    startOfParagraph: null,
    startTime: 50.26,
  },
  {
    duration: 0,
    content: "with Muk and it's poison gas",
    startOfParagraph: null,
    startTime: 51.3,
    pokemon: 'Muk.png',
  },
  {
    duration: 0,
    content: "Make one wrong move and it'll kick your grass",
    startOfParagraph: null,
    startTime: 53.3,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 55.18,
  },
  {
    duration: 0,
    content: 'How do you do the things you do?',
    startOfParagraph: null,
    startTime: 56.48,
  },
  {
    duration: 0,
    content:
      'Share with me your secrets deep inside (yeah, what kind, what kind)',
    startOfParagraph: null,
    startTime: 59.42,
  },
  {
    duration: 0,
    content:
      "What kind of Pokémon are you? Are you loyal through and through? And do you have a heart that's true? What kind of Pokémon are you?",
    startOfParagraph: null,
    startTime: 63.7,
  },
  {
    duration: 0,
    content: 'Uh yea yea yea',
    startOfParagraph: null,
    startTime: 74.92,
  },
  {
    duration: 0,
    content:
      'Reach higher with fire - go Flareon! Think twice about ice to be number one',
    startOfParagraph: null,
    startTime: 79.38,
    pokemon: 'Flareon.png',
  },
  {
    duration: 0,
    content: "Water's in order",
    startOfParagraph: null,
    startTime: 82.94,
  },
  {
    duration: 0,
    content: 'if you wanna be slick',
    startOfParagraph: null,
    startTime: 84.08,
  },
  {
    duration: 0,
    content: 'Mewtwo is the best',
    startOfParagraph: null,
    startTime: 84.84,
    pokemon: 'Mewtwo.png',
  },
  {
    duration: 0,
    content: 'when you get psychic',
    startOfParagraph: null,
    startTime: 86.84,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 87.34,
  },
  {
    duration: 0,
    content: 'How do you do the things you do?',
    startOfParagraph: null,
    startTime: 88.9,
  },
  {
    duration: 0,
    content: "Hitmonlee's the key for your fighting mood",
    startOfParagraph: null,
    startTime: 91.53999999999999,
    pokemon: 'Hitmonlee.png',
  },
  {
    duration: 0,
    content: "And you can rock 'n roll with Geodude",
    startOfParagraph: null,
    startTime: 93.53999999999999,
    pokemon: 'Geodude.png',
  },
  {
    duration: 0,
    content:
      "Dratini comes first when you choose dragon, but evolution's the solution if you're gonna win!",
    startOfParagraph: null,
    startTime: 98.28,
    pokemon: 'Dratini.png',
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 100.7,
  },
  {
    duration: 0,
    content: 'How do you do the things you do?',
    startOfParagraph: null,
    startTime: 102.28,
  },
  {
    duration: 0,
    content: 'Share with me your secrets deep inside (deep inside)',
    startOfParagraph: null,
    startTime: 105.36,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 109.12,
  },
  {
    duration: 0,
    content: 'Are you loyal through and through?',
    startOfParagraph: null,
    startTime: 111.52000000000001,
  },
  {
    duration: 0,
    content: "And do you have a heart that's true?",
    startOfParagraph: null,
    startTime: 113.3,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 115.6,
  },
  {
    duration: 0,
    content: 'Haha',
    startOfParagraph: null,
    startTime: 119.34,
  },
  {
    duration: 0,
    content: 'Geodude',
    startOfParagraph: null,
    startTime: 120.66,
  },
  {
    duration: 0,
    content: 'Give it up',
    startOfParagraph: null,
    startTime: 121.16,
  },
  {
    duration: 0,
    content: "Keep on training so you're stronger and faster",
    startOfParagraph: null,
    startTime: 122.88,
  },
  {
    duration: 0,
    content: "Just can't stop",
    startOfParagraph: null,
    startTime: 128.12,
  },
  {
    duration: 0,
    content: "'till your power I master",
    startOfParagraph: null,
    startTime: 131.06,
  },
  {
    duration: 0,
    content: "My plan is this: I gotta catch 'em all",
    startOfParagraph: null,
    startTime: 133.06,
  },
  {
    duration: 0,
    content: "Get 'em in my Poké Ball",
    startOfParagraph: null,
    startTime: 136.6,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 139.72,
  },
  {
    duration: 0,
    content: 'How do you do the things you do?',
    startOfParagraph: null,
    startTime: 146.34,
  },
  {
    duration: 0,
    content: 'Share with me your secrets deep inside, (deep inside)',
    startOfParagraph: null,
    startTime: 148.8,
  },
  {
    duration: 0,
    content:
      "What kind of Pokémon are you? Are you loyal through and through? And do you have a heart that's true?",
    startOfParagraph: null,
    startTime: 152.66,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 160.02,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 161.92000000000002,
  },
  {
    duration: 0,
    content: 'How do you do the things you do? (Ha, live it up)',
    startOfParagraph: null,
    startTime: 164.18,
  },
  {
    duration: 0,
    content:
      'Share with me your secrets deep inside, (deep inside) (No secrets from me)',
    startOfParagraph: null,
    startTime: 166.9,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 171.2,
  },
  {
    duration: 0,
    content: 'Are you loyal through and through?',
    startOfParagraph: null,
    startTime: 173.2,
  },
  {
    duration: 0,
    content: "And do you have a heart that's true?",
    startOfParagraph: null,
    startTime: 175.14,
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 177.14,
  },
  {
    duration: 0,
    content: "Yeah. I'll take a normal type like Jigglypuff",
    startOfParagraph: null,
    startTime: 186.54,
    pokemon: 'Jigglypuff.png',
  },
  {
    duration: 0,
    content: "Don't ya bug me with a Caterpie (Yeah that's what I'm sayin')",
    startOfParagraph: null,
    startTime: 189.54,
    pokemon: 'Caterpie.png',
  },
  {
    duration: 0,
    content: 'What kind are you?',
    startOfParagraph: null,
    startTime: 191.98,
  },
  {
    duration: 0,
    content: "Yeah, go Flareon, (ha, yeah that's my boy)",
    startOfParagraph: null,
    startTime: 196.06,
    pokemon: 'Flareon.png',
  },
  {
    duration: 0,
    content: 'What kind of Pokémon are you?',
    startOfParagraph: null,
    startTime: 198.06,
  },
  {
    duration: 0,
    content: "But don't get ground down by a Marowak",
    startOfParagraph: null,
    startTime: 203.57999999999998,
    pokemon: 'Marowak.png',
  },
  {
    duration: 0,
    content: 'Watch out for Mewtwo',
    startOfParagraph: null,
    startTime: 212.1,
    pokemon: 'Mewtwo.png',
  },
  {
    duration: 0,
    content: 'Oh yeah',
    startOfParagraph: null,
    startTime: 215.2,
  },
];

export default lyrics;
